### ISSUE TITLE
Importing Restrictions 

### ISSUE THREAD

**Issue by crumleyc** [biblibre/omeka-plugin-Import#2]
Uploaded the plugin like normal and It is only letting us create and importer for .csv files when we are trying to import everything but those. Curious to know if this sounds like a problem on our end or something else with version 0.2.0?

**Comment by jajm** [comment]
It is perfectly normal, as the plugin only implements a Reader for CSV files. But you should be able to implement your own Reader for any file format. Let me know if you need help to do that.

**Comment by crumleyc** [comment]
Well I guess I do need help. Im trying to import a JSON file, but there is no where to put the file or URL. Also thanks for the fast response!!

**Comment by crumleyc** [comment]
For example, we are wanting to parse URLs like this. https://dlg.usg.edu/record/geh_mas_ahc0695-027-004.json

**Comment by jajm** [comment]
I quickly made a skeleton plugin (https://github.com/biblibre/omeka-plugin-ImportReaderSkeleton)
All you need to do is to fill in the blanks (and rename some files and folders)
Take a look at the existing Csv Reader to know what each method should return.

**Comment by crumleyc** [comment]
I thought this plugin was dynamic enough to handle multiple inputs, where the CSV Import can only handle CSVs? The reason i ask is, these plugins are stored on the Universities servers and I dont exactly have access to the specific php files. I was hoping there would be a way to change the type of the Reader via the plugin.

**Comment by jajm** [comment]
> I was hoping there would be a way to change the type of the Reader via the plugin.

No that's not possible, sorry.
